### ISSUE TITLE
Smooth scale to position

### ISSUE THREAD

**Issue by inneke-dc** [moagrius/TileView#165]
Hi!
In my app I have a requirement that when I tap on a marker, I have to zoom in on that marker. It would be a combination of tileView.moveToMarker(view, true) and tileView.smoothScaleTo(maxScale, 500). Unfortunately, these two don't work together very well. I've found two closed issues like this one, but with no solution. Doing the move animation first and the scale animation after is not an option either, because if the point is at the edge of the map, it won't be in the center of the screen after the move animation. Could you add a method to zoom to a point and scale, or help me out how I would go about this? Thanks in advance.

**Comment by moagrius** [comment]
So the best way to do this would be to tween it yourself, then set the corresponding values with `moveToAndCenter( x, y )` and `setScaleFromCenter( scale )`.  You could use `ValueAnimator`, for example, and call those methods on progress.

I'll leave this open as a feature request since I'm planning on doing some updates week after next.

**Comment by moagrius** [comment]
With the latest release (version 2.0.0), this behavior has been corrected, and a convenience method `slideToAndCenterWithScale(double x, double y, float scale)` is available as a shortcut.
