### ISSUE TITLE
How to let multiple maps be deployed from SD Card to the mobile to this TileView frame

### ISSUE THREAD

**Issue by longhua68** [moagrius/TileView#182]
We have problems in letting maps be deployed from SD Card to  TileView frame. This is the structure of the code.
. Appreciated your response. We are new here!
![1](https://cloud.githubusercontent.com/assets/12317586/8004341/a5b580ee-0bb1-11e5-99b5-531d6a7ac8ba.jpg)

**Comment by moagrius** [comment]
I'm not 100% clear on your question, but I assume you're trying to get map tiles from SD rather than assets.  The default is from assets.  However, you can provide tiles however you want to implementing the `BitmapDecoder` interface.  Check out the [wiki](https://github.com/moagrius/TileView/wiki), and [this page](https://github.com/moagrius/TileView/wiki/Tile-Sources) in particular.
