### ISSUE TITLE
Limit the scaling upon pinch but why tileView auto-scroll to top boundary?

### ISSUE THREAD

**Issue by shidmei** [moagrius/TileView#197]
Hi, I have a tileView set to 0.1, 2.75 upon loaded but when pinch to zoom in the tileView, I need to restrict the scale to 0.75, 1.0 only.  I tried putting these codes into onZoomComplete:

tileView.setScaleToFit(false);
tileView.setScaleLimits(0.75, 1.0);
if(scaled < 0.75)
    tileView.setScale(0.75);
else if(scaled > 1.0)
  tileView.setScale(1.0);

it works and the scaling is limited to 0.75, 1.0 BUT the problem is, the tileView auto-scroll to the top of the boundary.  Can you advise why it behaves as such and if there's a workaround for this?  Thanks a lot.

**Comment by moagrius** [comment]
It will scroll to the closest point available at that scale.  If you want to keep the scrolled point relative, you'll have to do some math.  Are you using relative positioning?

**Comment by shidmei** [comment]
Hi, thank you so much for your reply.  I'm using defineRelativeBounds, is this what you mean by relative positioning?  Can it be like, after pinch, the map will stay at the position of finger down?  Please advise.  Thanks.

**Comment by moagrius** [comment]
Yes, that's what I mean.  Since you're immediately scaling it down, the scroll position will be constrained to what's visible.  Imagine if you had an image and reduced it's size - it would not try to center around where your finger was, it'd just resize.  You can probably do what you want to do, but will need to do some math - the most basic would be to figure out the relative scroll position - like `relativeScrollX = getScaledWidth() / getScrollX()`, then reset that after you set the scale set the scroll relatively, like `getScaledWidth() * relativeScrollX`.  That's just a basic idea, and you'd need to use `scrollTo` and figure it out for both axes, and if you want the center point you'd have to do quite a few more calculations, and if you want the actual thumb position, even more, but that's the basic idea.

LMK if that makes sense.

**Comment by shidmei** [comment]
HI, thanks again for the advice.  If not using my way of doing, is there any other simpler approach to achieve what I want?  Math calculation is too complicated for me.  :-)
Basically I just want to set the scale upon zoom in/out.  Please advise again.  Thanks a lot.

**Comment by moagrius** [comment]
If you're going to have major changes to scale like that, and you want the scroll position to update based on some logic you're defining, you're going to have to use math.  Sorry :)

**Comment by shidmei** [comment]
I see.  Noted.  Thanks for your advice and thanks for providing this great library.

**Comment by moagrius** [comment]
np, sorry there wasn't something built in - i may consider something like this in a future release if it looks like others are looking for similar features.
