### ISSUE TITLE
Pinch to zoom problem (first touch hits on marker)

### ISSUE THREAD

**Issue by sierbrat** [moagrius/TileView#220]
If first touch hits on marker, then tileview ignores second touch and zoom.
It's very noticeable when there are a lot of markers with high density of location.
In that case we need we need to hit free area with first touch, else it seems that pinch to zoom works badly.

**Comment by moagrius** [comment]
yes, touch events on children will consume that event before it gets to the parent, which is standard android behavior, and is discussed in the readme: https://github.com/moagrius/TileView#markers--callouts.  the workaround (mentioned in the readme) is to use a `MarkerEventListener` on the `TileView` instance itself, rather than on each marker.
