### ISSUE TITLE
Render during panning

### ISSUE THREAD

**Issue by peterLaurence** [moagrius/TileView#256]
Hey Mike,

This one is not an issue, it's just to ask you if you tried to make your TileView render tiles while panning/zooming. I was looking at your code today to start a custom implementation of parallel tile loading when i stumbled on how pan events are handled in TileView. I was surprised that TileView internally use RenderThrottleHandler, while i just expected render requests to be triggered by the end of a pan or a fling. I realized that the PanEnd event is fired at the end of a fling AND at the end of a pan.
I thought it would be simpler if the PanEnd is fired just once : at the end of the pan if there is no fling, or else at the end of the fling.

One modification leading to another.. i realized that we can render while paning/zooming without stutter.
You can have a look at my [repo](https://github.com/peterLaurence/TileView/commits/render-during-pan), branch "render-during-pan". But just to be clear : these are quick and dirty modifications. But it works, so i'd like you to know.

The behavior in the demo is amazing :) I don't even have anymore the issue #252.

**Comment by moagrius** [comment]
interesting - i'll check it out - have you tried the version without debounce using tiles from a network source (e.g., http)?

**Comment by peterLaurence** [comment]
No i haven't tried with network source, because i plan to implement asynchronous tile loading, as @bnsantos said. This implementation would be more suited for network source.

**Comment by mkmckenna** [comment]
Hi Moagrius/Peter

I'm going to post this question here as its slightly related. Btw I have also done some customization of the panning and zooming logic so that it does this while doing these actions and it seems to work. Thats interesting though about it being called twice. I wonder if thats got something to do with some of the warnings I am seeing.

Anyway, I've recently moved to V2. I had a pretty big switch over rewrite to do for a number of reasons not really to do with TileView however.

One issue that I'm having though is I have a rendering task that is kicked off when TileView launches. This renderer basically builds loads of paths, draws them to a canvas and I make my own custom tiles out of it and overlay these over my base tile set and store them in cache to be used. Its all quite complicated but it works. 

What I'm having issues though with is when this task ends I try and call requestRender() but nothing seems to happen. My brain is slightly fried and its late so maybe im missing something here, but im sure in v1 this method worked correctly.

Btw V2 is a vast improvement. Brilliant work!

Cheers,
Martin

**Comment by moagrius** [comment]
@peterLaurence 

> No i haven't tried with network source, because i plan to implement asynchronous tile loading, as @bnsantos said. This implementation would be more suited for network source.

i think those are 2 separate issues.  if the core library reflects the changes in your fork removing the throttle, i suspect it might make fetching tiles from remote sources jumpy.  that said, i could see this as an option: off the top of my head, maybe something like a new method, `setShouldRenderWhilePanning(boolean shouldRender)`, that sets a flag that skips the throttle (per your fork), while default behavior includes the throttle.  I'd be happy to make that update next time i'm working on this project (after tests, etc, of course) - or you're welcome to create a PR if that sounds like something you'd like to do.

also fwiw, tiles are decoded asynchronously, just one a single background thread, instead of one-thread-per-tile (as it should be).  i know you're already aware of that, but for posterity :)  i do intend to correct that, either with @bnsantos repeating the work he did for v1, or you doing it in a new PR, or me doing it next time i'm on this project.

@mkmckenna render requests are throttled and debounced, so i wouldn't be concerned if they were being called too often.  

> What I'm having issues though with is when this task ends I try and call requestRender() but nothing seems to happen.

Hard to say exactly why it's not working for you, but keep in mind there's a _lot_ of tests to make sure we running as efficiently as possible - we check if there's already a pending request, if the request state has not been cancelled, if the tile set is he same as the last one that was rendered, etc.  My guess it that the same intersection were already rendered, so it thinks its work is already done.  Try `getTileCanvasViewGroup().clear()` before calling `requestRender()` again.

If that doesn't work, you can skip some of these with a shortcut - not necessarily recommended for the long-term, but just to test, you might try `getTileCanvasViewGroup().renderTiles()` - other than that, all I can suggest is logging all the connected render methods.

HTH

**Comment by peterLaurence** [comment]
@moagrius 

I took the time to find a proper way to achieve render while panning. I introduced `setShouldRenderWhilePanning(boolean shouldRender)`. The throttle is not removed, it is just avoided if `shouldRender` is set to `True`. Also, instead of completely avoiding `TileCanvasViewGroup`'s `TileRenderHandler`, it is used but with a much smaller delay. That way, the number of rendering tasks is still limited.
I tested without debounce, and it isn't jumpy :)
So for all this, i make a PR.

While i was testing i noted that every rendering task is given the list of visible tiles, without taking into account the tiles already rendered. In fact, they are but each time the `TileRenderTask` adds a tile to the view. This is particularly visible when using tiles from a network : when the visible area overlaps an area already rendered, all the tiles already rendered are rendered again. I believe there is an optimisation needed here (my next PR i guess :).

@mkmckenna 
I don't think this is related to your problem, because even if the PanEnd event is called twice, it is properly handled in the `TileView`, like @moagrius explained.

**Comment by mkmckenna** [comment]
@moagrius 
Thanks Mike.

Turns out it was one of the checks. Basically it thought it had already rendered that detail level. I got around it for the moment by suppressing rendering until my own overlay renderer is finished then calling requestRender.

@peterLaurence 
Sounds interesting. Look forward to hearing what more you come up with!

Cheers,
Martin

**Comment by moagrius** [comment]
@mkmckenna cool, glad you got it worked out.  might be worth adding a method to force a recompute...?

@peterLaurence 

PR looks good, thanks for doing that.  There's a couple notes about a small style change and versioning; after that I'll merge.

Regarding this:

> While i was testing i noted that every rendering task is given the list of visible tiles, without taking into account the tiles already rendered.

Gah - you're right - not sure how that slipped past.  That's a lot of work decoding tiles that are already rendered, so this is pretty critical.

I'm at work so didn't have a ton of time to investigate, but it might be as simple as changing this:

```
LinkedList<Tile> getRenderList() {
  return (LinkedList<Tile>) mTilesScheduledToRender.clone();
}
```

To:

```
LinkedList<Tile> getRenderList() {
  LinkedList<Tile> renderList = (LinkedList<Tile>) mTilesScheduledToRender.clone();
  renderList.removeAll( mTilesAlreadyRendered );
  return renderList;
}
```

If you have the time and inclination to patch this, great, I'll keep an eye out for a PR.  if not, I'll get to it as soon as i can.

Thanks again.

**Comment by peterLaurence** [comment]
@moagrius 

> If you have the time and inclination to patch this, great, I'll keep an eye out for a PR. if not, I'll get to it as soon as i can.

Yes, i will look into this. I think it will be the last step before implementing the on-thread-per-tile, now that i have a better understanding of how `TileView` really works.

**Comment by moagrius** [comment]
awesome, thank you
