### ISSUE TITLE
Unnecessary load of tiles from the highest scale `DetailLevel`

### ISSUE THREAD

**Issue by peterLaurence** [moagrius/TileView#259]
When double-tap is used at maximum scale to go back to the minimum scale, the tiles from the `DetailLevel` at maximum scale are rendered, instead of the ones from the current `DetailLevel` (after double-tap). 

To see that, just log as follows :
```
@Override
  public void onScaleChanged( float scale, float previous ) {
    super.onScaleChanged( scale, previous );
    mDetailLevelManager.setScale( scale );
    mHotSpotManager.setScale( scale );
    mTileCanvasViewGroup.setScale( scale );
    mScalingLayout.setScale( scale );
    mCompositePathView.setScale( scale );
    mMarkerLayout.setScale( scale );
    mCalloutLayout.setScale( scale );
    System.out.println( "scale : " + scale );
    System.out.println( "current scale : " + mDetailLevelManager.getCurrentDetailLevel().getScale() );
  }
```
Zoom in whatever demo to max scale an then double-tap. The tiles rendered afterwards have a "current scale" that is the same as before the double-tap. In other words, a lot of tiles may be requested to be rendered, especially on a map with many `DetailLevel`.

**Comment by peterLaurence** [comment]
Removing the `DetailLevel` lock in `TileView` solves the issue. No jumpy behavior when zooming accross `DetailLevel` changes.

```
@Override
  public void onZoomBegin( float scale, Origination origin ) {
//    mDetailLevelManager.lockDetailLevel();
    mDetailLevelManager.setScale( scale );
  }
```
@moagrius 
But i guess you did that on purpose. Can you explain why you introduced that lock?

**Comment by moagrius** [comment]
> But i guess you did that on purpose. Can you explain why you introduced that lock? Perhaps you were concerned that a DetailLevel change during a zoom (programmatic or not) would cause some issue?

Yes, definitely intentional.  Imagine someone was right at the edge of 2 detail levels (say .48 with a registered detail level of 0.25 and 0.5), and they started pinching, a little larger, a little smaller - without the lock, _all_ visible tiles are going to re-rendered _on top of_ the previous set, _each time there's a change_, so not only is that a ton of extra computration and a hit on performance, the likelihood of OOM is very high as well.

By locking the zoom level during a pinch, we ensure that the tiles that were visible when the pinch started scale, but are not swapped out _during the pinch_, although they may be replaced after the pinch is complete.

LMK if that doesn't make sense.

**Comment by peterLaurence** [comment]
Ok noted. So i need to avoid the lock just in the particular case of a double-tap at max scale.

**Comment by moagrius** [comment]
:thumbsup:

**Comment by peterLaurence** [comment]
I tried to do what you described : on a `DetailLevel` change limit, it tried to zoom in/out the fastest i could to see the impact on memory use. I could not produce any memory peak.
But i agree that the lock prevents some memory allocation that can be avoided, thus saving a little more battery life.

**Comment by peterLaurence** [comment]
As i can't reproduce this since 2.1.0, i believe we can close this.

**Comment by moagrius** [comment]
:thumbsup:
