### ISSUE TITLE
I have a Map in EPSG 25833 coordinate system. It is possible to use these and how ?

### ISSUE THREAD

**Issue by Bukmop89** [moagrius/TileView#267]
I have a Map in EPSG 25833 coordinate system. It is possible to use these and how ?

I only can see lon lat coordinate system

**Comment by peterLaurence** [comment]
You can, but you have to do the calculations yourself (e.g. convert lat/lon to the projected coordinates  ; the projection is transverse mercator in your case).

If your map is not too big, using linear interpolation between bounds expressed in lat/lon will produce a neglieable error on positioning.

**Comment by moagrius** [comment]
the positioning system uses linear interpolation, as Peter mentioned, meaning that all it cares about is the difference between whatever bounds you set up.

the method `public void defineBounds( double left, double top, double right, double bottom )` defines the edges of your area, and any number passed in will try to figure out where it is between those edges.

pretend you passed `defineBounds(3, 3, 5, 5)` and then you used a positioning method like `moveMarker( marker, 4, 4)`, then the TileView will move the marker to exactly 50% of the distance between the left and right edges, and the top and bottom edges, because 4 is exactly 50% of the distance between 3 (left) and 5 (right).  If you passed `moveMarker( marker, 4, 3)`, it'd move the marker to 50% of the distance between the left and right edges, and at the top edge.  LMK if that doesn't makes sense.
