### ISSUE TITLE
Drawing a path on map between two points taking into account buildings

### ISSUE THREAD

**Issue by eldursi** [moagrius/TileView#279]
First of all thank you, the library is amazing.
So I'm using this library to display a map as an image, and I was wondering if there was a way to draw a path between two points taking into account the buildings, i.e. the path only gets drawn on the pathways. Is there a way to do that? maybe by overlaying a graph and setting it to invisible and using dijkstra algorithm?

**Comment by Dev-iL** [comment]
The navigational part of your issue seems off-topic to me, since this library deals with the display of images (or maps), and not navigation.

Regarding the display of paths - this is described in the [readme](https://github.com/moagrius/TileView#paths). If the standard path-plotting method isn't good for your needs, you might be able to use an invisible [scaling layer](https://github.com/moagrius/TileView#add-my-custom-view-to-the-tileview-so-that-it-scales) (such as the one hotspots are put in), on which you put your "paths viewgroup".

**Comment by eldursi** [comment]
Thank you very much
