### ISSUE TITLE
Zoom a single image

### ISSUE THREAD

**Issue by cuocsongquanhta** [moagrius/TileView#287]
How to zoom a sigle image with marker is added?

**Comment by moagrius** [comment]
Please restate your question with more information.

**Comment by cuocsongquanhta** [comment]
In your sample, you load image from 4 slice. My question means how to load whole image  but don't need to divide it to 4 slices.

**Comment by moagrius** [comment]
You could use a single image, but if you exceed the device's heap limit (which can be as low as 16MB on old devices), you'll crash.  The intention of the library is to manage tiled image so that you're not constrained by the bitmap budget, but there's nothing stopping you from using the normal methods with a single "tile".  No special coding is necessary.
