### ISSUE TITLE
Rendering bugs

### ISSUE THREAD

**Issue by tsuijten** [moagrius/TileView#319]
Occasionally when zooming I see rendering bugs:
- No tiles drawn
- Subset of tiles not drawn

I attached a screenshot showing an example. This happend when quickly zooming out, my screen became blank (no tiles were drawn). Then when slowly zooming in again some tiles showed up but not all of them.

I've been trying to figure out what's going on myself, but it's like finding a needle in a haystack :)

![screenshot_20160614-090823](https://cloud.githubusercontent.com/assets/772711/16034135/515c12de-3210-11e6-817a-42c8baad22a4.png)

**Comment by peterLaurence** [comment]
Have you tried `TileView.setShouldUpdateDetailLevelWhileZooming( true )`? It may fix that issue.

**Comment by tsuijten** [comment]
I have `setShouldUpdateDetailLevelWhileZooming` set to `true`. It's actually quite easy to reproduce and I get inconsistent results frequently when quickly zooming in and out.

Some more examples, in these examples I added a background images which clearly illustrates what's going wrong (I also added some debug drawing lines to show the tiles):
![screenshot_20160614-092018](https://cloud.githubusercontent.com/assets/772711/16035581/2f99fafa-3218-11e6-8c09-84c954ccf563.png)
![screenshot_20160614-092011](https://cloud.githubusercontent.com/assets/772711/16035583/31f886c2-3218-11e6-999d-63bc9a3b0c8d.png)
![screenshot_20160614-100036](https://cloud.githubusercontent.com/assets/772711/16035585/3421837c-3218-11e6-80e2-a749570afec5.png)

**Comment by peterLaurence** [comment]
I think that the tiles drawn at wrong zoom level is a side effect of setShouldUpdateDetailLevelWhileZooming set to true. 
Can you confirm that you don't have tiles drawn at wrong zoom level with this option set to false?

**Comment by peterLaurence** [comment]
Also, about the missing tiles, have you tried the last version from source? If you look at my last commit, it fixes #252 which looks like your issue.

**Comment by tsuijten** [comment]
I have the latest code. Even with `setShouldUpdateDetailLevelWhileZooming` set to false I have issues with tiles not rendering. So #252 doesn't seem to be fixed.

**Comment by peterLaurence** [comment]
Well i have never seen such an issue. The root cause of your issue is probably different from #252 (which, i admit, has a too broad description title).
Are you working with local tiles? It looks like you're testing with the demo app, so the tiles are contained in an asset.

**Comment by tsuijten** [comment]
I'm working with the painting demo straight out of the box.

I've been playing around, if I completely remove the `TileRenderThrottleHandler` and call `beginRenderTask` directly from `requestRender` my issues seem to go away.

**Comment by peterLaurence** [comment]
Haha you remind me when i discovered TileView.. the first thing i did was to remove the `TileRenderThrottleHandler`.
Anyway, this doesn't sound good. Does the version you're testing includes your PR? Are you using `setShouldScaleToFit( true )` or something else?
In fact, you should tell us exactly how you use TileView so we can try to reproduce the issue.

**Comment by peterLaurence** [comment]
Sorry but i just tried with the latest version, and i couldn't reproduce it.

**Comment by tsuijten** [comment]
I'm testing with the `master` version from your repo (so without my changes). I regularly get render errors when zooming in and out (regardless of `setShouldRenderWhilePanning` is true or false). Especially when keeping your fingers on the screen and making zoom in and out gestures repeatedly.

So there must be going something wrong somewhere. I'll try to pinpoint myself what could be going wrong, but it's not easy :)

**Comment by peterLaurence** [comment]
Oh... but at the time i am writing this, the `master` branch of my repo is 10 commits behind the origin one. So you don't have the latest version.
I am updating my repo right now.

**Comment by peterLaurence** [comment]
Done!

**Comment by tsuijten** [comment]
Ah, I get there is some confusion. I don't see any new commits here on the master branch: https://github.com/moagrius/TileView/commits/master

Exactly what version should I be testing?

**Comment by peterLaurence** [comment]
I tested the last version of @moagrius `master`, which is now the same as my repo's `master`.

**Comment by tsuijten** [comment]
I've been digging around for a couple of hours, haven't found it yet... I'm pretty sure there is a bug in there somewhere that causes this. It's easier to reproduce when `setShouldUpdateDetailLevelWhileZooming` is set to true.

**Comment by moagrius** [comment]
nobody's waiting on me for any of this, right?  please @ me if i need to be involved - ty

**Comment by peterLaurence** [comment]
@moagrius i'm stuck here. Basically he has an issue i can't reproduce, and i have suggested him all the workarounds i could think of.

**Comment by peterLaurence** [comment]
@moagrius @tsuijten Oh dear.. in fact i just reproduced the issue.

To reproduce, from master, in `LargeImageTileViewActivity`, do the following :

- comment out `tileView.setShouldLoopScale( true );`. Double-tap zoom-out will be useful.
- add `tileView.setShouldScaleToFit( false );`
- change `tileView.setScale( 0 )` to `tileView.setScaleLimits(0.1f, 1f)` 

Then double-tap several times to zoom-in and zoom-out. Do that until some of the issues described in OP shows up on zoom out.

**Comment by peterLaurence** [comment]
According to my tests, it doesn't happen if we use `tileView.setShouldScaleToFit( true )` (the default).

**Comment by peterLaurence** [comment]
Found a fix. But i need to be sure this is the right way to fix it.

**Comment by tsuijten** [comment]
I'm pretty sure it also happens when `setShouldScaleToFit` is set to true, only it's harder to reproduce then. I'm invested in fixing this issue since TileView is gonna play a large role in a new app I'm creating. So far I've tested various thing but I haven't found the source of the bug yet...

@peterLaurence @moagrius Maybe you guys can shoot me an email at thijs[at]q42.nl maybe we could get in more direct contact in order to fix this bug? Your effort so far is much appreciated 👍

**Comment by peterLaurence** [comment]
Don't worry we will fix that.

**Comment by peterLaurence** [comment]
@tsuijten I created to branch try_to_fix-#319 on my fork :
https://github.com/peterLaurence/TileView/tree/try_to_fix_%23319

I fix the issue for me. You can test it if you want. 
I am not quite satisfied with the way i've done this. But this is the best i got for now.

My understanding of the problem is that the last drawn `TileCanvasView` is being cleaned up while it should not. The workaround i introduced forces the redraw after a `DetailLevel` change.

**Comment by moagrius** [comment]
Hey guys...  so my feelings are:

1.  I don't want to interfere if you guys have momentum - just LMK if so
1.  I don't think your fix is terrible @peterLaurence - it does feel like you're working around some old bad decisions as it evolved (mostly by me), but I think it's OK
1.  @tsuijten do you have any working fix on a branch (or even a strategy)?
1.  This issue would be fixed if I finally did the migration to the single `Canvas` that I've talked about before, and `invalidateRect` calls - there'd be no more weird `DetailLevelChange` behavior because we wouldn't have to wipe the last level and risk OOM as we draw a new one on top - we'd only ever have the single drawing surface, and pieces would be overdrawn (again, via `invalidateRect`).  I've been thinking about this long enough that I think I have a pretty decent strategy, and I think that if done correctly it'd eliminate a lot of clunky code (where most of our bugs pop up now).  That said, it's a fairly big change.  I can some time every week but TBH I'm not sure when I'd be done...

Should I spend the time doing that?  Do we want to commit @peterLaurence's patch for now?  Does it reliably fix the issue?  Should I butt out and let you guys finish what you've started?

**Comment by tsuijten** [comment]
Hi Mike,

I don't have a fix, I've been trying various things to get a sense of why the bug occurs. But I'm new to the codebase so I haven't found/fixed anything yet.

If you think this problem has a root cause that should be fixed like you explained at `4.` I would definitely say "got for it"!

In the mean time I'll test @peterLaurence's fix to see if that solves my problem for now.

**Comment by peterLaurence** [comment]
@moagrius Excellent news! I don't mind spending a little time fixing this even if it will be replaced by a new major version. As usual, you can count on me for code review, tests, etc.

**Comment by moagrius** [comment]
ok, i'll get on it this weekend - not sure how long it'll take but i'll keep you posted.  thanks both

**Comment by tsuijten** [comment]
Awesome @moagrius!!

I can't wait to show you guys what I'm working on. It'll be a fantastic showcase for TileView IMO :)

**Comment by moagrius** [comment]
hey guys - here's what i've got so far: https://github.com/moagrius/TileView/compare/tile-canvas-states?expand=1

it accomplishes the basic goal (get rid of multiple canvases - draw everything to a single canvas), and simplifies a ton of stuff, but it still needs some work:

1.  transitions are goofy.  i didn't have much time by the time i started looking at this; probably fairly simple fix
2.  the case i was worried about with changing detail levels is not solved.  imaging you have 2 details levels over a building - the "farther" away level shows the roof, streets, rivers, etc.  the "closer" in one shows the interior of the building (walls, bathrooms, etc) as if the root was removed.  as we move from one detail level to the next, we want the new pixels to be drawn on top of the old pixels, so you never see a flash of white (or whatever background color).  i was hoping to be able to handle this entirely with validation, but realized that was probably too optimistic (and it was).  that said, _worst case_ we just draw to an offscreen bitmap and render that on the canvas (so anything already drawn will stay until we draw over it), _but_ this requires a little more housekeeping to keep memory use down (i need to clear any pixels that we really don't want).  i don't think it's a big deal, but am out of time for the weekend.

i hope to be able to get a little more time this week, but might not be until next weekend (i have a minor surgery this week, and of course day job).  @peterLaurence if you want to take a shot, feel free - just grab the branch and run the demo and you'll see immediately what needs done.  @tsuijten not sure what your comfort level with the core library is at this point, but if you'd like to take a shot i'm sure Peter and i would welcome the help (not to speak for you, Peter).

overall i'm really happy with the basics of what got done - i haven't spent a ton of time on every line or optimization, but i removed quite a bit of code, and simplified a lot more, and that always feels good.  i'm not issuing a PR yet (because it's not ready for merge), but feel free to provide any feedback.  if it's easier to create a dummy PR just so you have line comments, that's fine - we'll just delete when done.

fwiw, the basic idea is that we draw all tiles to one canvas.  that canvas scales it's own pixels like normal.  each tile is *un*scaled for it's detail level (so if the detail level is .75, the tile should be 150% size) - this happens in `Tile.draw` - note that it needs to happen like it is (by passing in transformation rects), and not actually scaling the bitmap with something like `createScaledBitmap` - we actually need all the pixel data, and all transform are necessarily temporary and transient.

post back with questions.

thanks

**Comment by peterLaurence** [comment]
Ok Mike i just had a first glance on the changes (good job!). I agree that a single canvas should alleviate the library. But before going further into the implementation i think we should precisely write down what we really want to do. I am saying that because something surprised me in the way tiles are drawn.

Like you, i think that invalidating the visible area should trigger the drawing of the tiles of the current detail level. But i see that in the current implementation, if the detail level changes, the new visible tiles are actually added to a maintained list of tiles rendered (`mTilesInCurrentViewport`). This is when new tiles are down on top of older ones. Then, during the cleanup, all tiles from `mTilesInCurrentViewport` that do not belong to to the visible tiles of the current detail level are removed from the canvas.
Is this intentional? I would rather have expected the invalidate call to simply retrieve the new list of tiles visible for the current detail level and render them on the canvas, and keeping the old tiles into memory would not be necessary. Maybe i'm too optimistic here...

As a side note, unless i missed something, the detail level change logic isn't touched. In other words, we don't want tiles from different detail levels to be visible in the same time (i'm ok with this). So we'll still have the potential OOM when zooming out quickly through several detail levels. But i have thought of some solutions so this not a big deal. For now, i think we should focus on the new render logic and have good transitions, etc.

Correct me if i'm wrong.

Btw, good luck for you surgery.

**Comment by moagrius** [comment]
Hey Peter,

The big reason why we don't just redraw visible tiles each time is because of the decode operation - that takes times - if we start over with each render request, there will be lots of blinking and flashing as existing tiles get discarded and redrawn.

Also, just to clarify, each tile _invalidates only it's own rect_, not the viewport, which provides a lot of benefits.

I agree it's a good idea to write out the goals and strategies of the implementation.  That said, I have to shut down fairly soon for my early appointment tomorrow and probably won't be back on for a couple days.

Thanks for your input - I think if we can get each other on the same page, we'll be good to go.  Feel free to mess around with that branch and try out any different ideas you might have.

**Comment by tsuijten** [comment]
Hi Guys, thanks again for your effort! So cool you are so actively developing this library!

I've been playing around with this branch, I still get a lot of weirdness. I have the feeling that there is a more "fundamental" issue that's causing problems. There is a lot of state kept which makes for a steep learing curve. I've been stripping down the `TileCanvasViewGroup` and playing around with it to wrap my head around it. But I'm not that comfortable with the core library yet to make fundamental changes.

It would be great if we could prevent the flashing  / flickering by drawing pixels "on top" of the old detail levels. But I agree to first get a stable and reliable core and then optimize further to prevent flashes

**Comment by peterLaurence** [comment]
Ok Mike. Will have a look with that in mind. I think I will have time to do that in a few days.

@tsuijten Yes Mike warned that it is just a work in progress and there are fundamental issued to fix.

**Comment by moagrius** [comment]
@tsuijten thanks for your feedback.  as @peterLaurence said, it's a win/poc, but we now have a handle on the issue.  we'll definitely be able to work out the drawing artifacts from here

**Comment by moagrius** [comment]
hi guys - didn't have a ton of time this weekend, but i did try a couple things.  

drawing to an offscreen bitmap is a no-go since it's just too big - bitmap sizes are immutable, and it allocates space for transparent pixels, so i don't see any way to make it happen.  there's a small chance that we could create bitmap the size of the viewport, but that gets complex quickly - if we just move it (without resize), we have to redraw each pixel, offset by the distance moved, on each scroll - which sounds dicey.  if we could just resize, it's be pretty straightforward, but we can't resize the bitmap without destroying and recreating, which is a heavy operation, especially for something we'll need to do during scroll.

i also tried saving the last detail levels tiles that were rendered in a separate `Set`, but didn't get too far with that so far, but i also haven't hit any major snags that make me think the approach won't work.  ideally, we'd get a `Region` of everywhere the new tiles were drawn to, and exclude any old tiles that are under that `Region`, but with transitions that gets hairy as well, basically the region would be anywhere a _new_ tile has been drawn at full opacity...  that's something i'd like to pursue, but not sure if i'll be able to get back to this today.

i'd really like to get this feature at least functional by next weekend - will do my best.

if either of you would like to take a shot, feel free, but no pressure :)

**Comment by tsuijten** [comment]
I took a big step :)

I started rebuilding tile viewer from scratch (based on the `ZoomPanLayout`) I feel I've setup an architecture that is much simpler, less prone to errors and more performant. Additionally I added some features to prevent flickering when switch detail levels.

I want to share what I have right now. It's far from "library-mature" and I removed all the code (and features) I did not need (like markers etc). But I hope you get a sense of my thoughts. I use this version in my app right now and it works like a charm :)

I hope we can use some of my work in the "real" TileView lib some day.

Link to my code (which is Kotlin btw) https://github.com/tsuijten/TileView/blob/feature/redesign/tileview/src/main/java/com/qozix/tileview/TileView.kt

**Comment by moagrius** [comment]
nice job.  correct me if i'm wrong, but the bottom line is just that your'e drawing the previous detail level beneath the current detail level, right?  unfortunately that's exactly what we're trying to avoid.  on a large map, or one without sufficient detail levels, or on a large screen with a small heap, this _drastically_ increases the chance of OOME.  the entire point of my current work is to draw onto a single canvas, that's only as large as the visible viewport, yet visually appear to support previous detail levels, transitions, etc.

also, fwiw, this task is pretty straightforward without transitions.  adding tile transitions (which can be partial, between detail levels, etc) makes it much more difficult - imagine for example that someone has a partially transitioned tile, then changes detail level, gets more partially transitioned detail levels, then changes detail level again - there are pixels that should display all 3 states, stacked...  as you can see, bookkeeping becomes critical.  my initial thought was to just draw to a bitmap, so new pixels are drawn over old, but unfortunately since Android bitmaps are size immutable, as soon as a bitmap is created that's as large as the tileview, it OOME.  creating one and resizing it is impossible, so the only potential outlet here it to draw one, then transform it, but i think that's A) too limited, B) too complex, and C) not certain to solve the problems.

at this point i'm reasonable certain that i'll need to draw to a single canvas, and keep track of state manually.

if the very simple version you have works for you, by all means go for it, but unfortunately it's not going to cover the broad use cases this library has to support.

**Comment by tsuijten** [comment]
I do keep the previous detail level, however I make softreferences from the bitmaps, so if there is memory pressure they can be cleaned up. After a delay the old detail level is cleaned up (assuming the new tiles are loaded)

Indeed I removed transition support because it makes things more complicated.

I agree my changes will not be sufficient for you library. However I feel there are some concepts that I feel simplify the code and has less state that ar usefull for the library. Like putting the tiles in a 2d list and looping through that instead  of creating `Set`s of visible tiles all the time

**Comment by moagrius** [comment]
very cool, i'll take a look at those pieces and see if any of it works with the changes i'm working on now.  thanks

**Comment by lukast008** [comment]
Hello,

I have the same issue in my application. During scrolling/zooming some tiles are missing or appearing incorrect ones (from different zoom levels).
I would like to add that I have just upgraded the lib from version 1 to 2.1.7. Before I didn't notice any problems.
What is the status of this issue now?

Best regards

**Comment by moagrius** [comment]
it's being actively worked on.

can you confirm you're seeing the bug in 2.1.0 and 2.0.10?

**Comment by lukast008** [comment]
Thanks for your reply.
Now I use the newest version (2.1.7).

**Comment by moagrius** [comment]
thanks.  can you try those other version i mentioned tho, to see if the bug is present in those version?  it will help us debug

**Comment by lukast008** [comment]
I tried those other versions. The bug is present.
I have also noticed that with simple tiles it almost doesn't happen. I tried the same map with tiles 256x256 (png). In first test tiles were very simple (around 1KB) and it looked quite ok. In the second test I used tiles with more complex texture (around 50KB) and the mentioned bug occured often.

**Comment by moagrius** [comment]
thanks for checking that out.

i've refactored tile rendering entirely (we use a single canvas now), and i've spent many hours this week trying to generate drawing artifacts or bugs and can't see any.  this issues you described specifically appears to be fixed.

> During scrolling/zooming some tiles are missing or appearing incorrect ones (from different zoom levels).

i still need to optimize and clean up, but the core feature is done.

@peterLaurence are you around for a code review, probably early next week?  also @tsuijten i'd be happy to have your feedback as well, when it's ready

**Comment by peterLaurence** [comment]
@moagrius yes i will be available until the last week of August.

**Comment by moagrius** [comment]
@peterLaurence hmm are you going to be off github permanently after August?  i'd hate to see you go, but don't want to pry too much into your personal situation...

anyway, i moved the most recent refactor to it's own repo - the whole thing is a bit of a mess, it's branched off a branch of the main repo but the main repo didn't get copied over, etc - and the branch i'm on (`complex-draw`) is in it's most bare working state - i've left a ton of cleanup not done and there are a bunch of logs - i'm thinking those logs might be helpful to see what's going on exactly.  i've also enabled transitions and put a set a really long duration so the behavior is more obvious, but feel free to change/tweak any settings or features...  the repo is https://github.com/moagrius/TileViewLabs and the branch i'm working on is https://github.com/moagrius/TileViewLabs/compare/master...complex-draw?expand=1 - if you want to clone it and run it, and just verify that everything works and is fixed and generally do a sanity check, i can migrate the changes to this (original) repo, cleanup, and submit a legit/normal PR for review...  does that sound OK?  if you'd rather just do it normally, or find my MVP a little too messy to work with, NP just let me know and I'll fix it up and submit a normal PR, here...

any feedback is welcome.

also, i really think that we're getting to a point where a V3 (with breaking changes) is going to be helpful - i had to keep a lot of legacy stuff up just so existing builds don't break - a big mistake was exposing things like `getTileCanvasView`, which means we have to support all those different APIs.  anyway, i'm open to any ideas you have about V3 if you're interested (and available).

@tsuijten feel free if you'd like to take a look at the branch linked above and confirm that those changes would indeed fix your issue.

**Comment by peterLaurence** [comment]
@moagrius don't worry, i will just be on holidays (abroad) from 28 August to 11 September.  During that time i will just be able to check my emails from time to time.
So i understand the changes being made are important, and i will start looking at this new repo this week.
I agree the v3 idea, as (if i understood correctly) some apis like `setShouldUpdateDetailLevelWhileZooming` won't make any sense anymore. I have some details in mind that could be fixed while were doing a revamp, but i guess the priority is to get something working with the new architecture set.
I hope i won't have to ask you for a cleanup..

**Comment by moagrius** [comment]
all sounds good, thanks Peter

**Comment by peterLaurence** [comment]
I have reported my first issue on https://github.com/moagrius/TileViewLabs

**Comment by moagrius** [comment]
2.2 has been released and should fix this issue.  Please post back if not, and thanks @tsuijten for your help and feedback.

**Comment by tsuijten** [comment]
Thanks a lot @moagrius and @peterLaurence !
