### ISSUE TITLE
Are these 5 lines codes exactly meaningful?

### ISSUE THREAD

**Issue by parcool** [moagrius/TileView#332]
In 'ZoomPanLayout.java', the 'onMeasure(int widthMeasureSpec, int heightMeasureSpec)' fuction has 5 lines codes like this:
`        int width = MeasureSpec.getSize(widthMeasureSpec);
        int height = MeasureSpec.getSize(heightMeasureSpec);
        width = resolveSize(width, widthMeasureSpec);
        height = resolveSize(height, heightMeasureSpec);
        setMeasuredDimension(width, height);`

I want to know why not use 'setMeasuredDimension(widthMeasureSpec, heightMeasureSpec);' to replaced?

**Comment by moagrius** [comment]
setMeasuredDimension takes dimensions as arguments.  A measureSpec is an int but it combines a dimension with a bit flag.

**Comment by parcool** [comment]
i delete the four lines which you code and add the `setMeasuredDimension(widthMeasureSpec, heightMeasureSpec);` to replace these,rebulid and rerun,nothing changed with the map!

**Comment by moagrius** [comment]
sir, onMeasure takes ints that are not dimensions, but a value combining a dimension with an intent flag.  setMeasuredDimension takes dimensions, not a combined value.

you don't see any difference because you're probably using TileView to fill the screen.  onMeasure determines the size the parent should consider the instance when laying it out, especially as regards other children.  you might see differences if the TileView were passed in different layout values (e.g., WRAP_CONTENT, fixed size, etc) and is laid out with children.

None of this has anything to do with TileView.  this is basic Android layout stuff.  please read the Android documentation for questions like this.
