### ISSUE TITLE
Layers and Paths

### ISSUE THREAD

**Issue by zhaoxuhui** [moagrius/TileView#336]
Question 1:I'm wondering whether the tileview supports showing different layers.For example,there are kinds of maps .When I click text "2016" it will shows the map of 2016,when I click "2015" it will show the map of 2015.How to reset the content of tileview and refresh it?
Question 2:How to use the method public void removePath(DrawablePath path) in CompositePathView class ?How to specify a certain path and delete it?Now I just know using clear() to remove them all.
Question 3:Can we register different response event to different paths drawn by tileview?For example when I click path 1 it will show info about path 1,when I click path 2 it will show info about path 2.

**Comment by moagrius** [comment]
1.  You can use `resetDetailLevel` to clear previously registered levels, and add different ones
2.  You can instantiate a `DrawablePath` directly, or some methods return instance.  Pass the instance to `removePath` and it will be removed
3.  DrawablePaths don't have any touch events, but you can create a HotSpot with the same Path instance (although it will be filled, not just the line of the path).  You're free to use your own views or touch system.

**Comment by krabo0om** [comment]
@Q1
It clears the levels but does not reset the tile's image. Is there a way to force this?
I illustrated it in this [video](https://youtu.be/dWOxM1UE-j4). For some of the tiles there is no new image in another floor (the `BitmapProvider.getBitmap()` returns `null`).
Zooming/Panning the "broken" tiles out of view solves the issue.

**Comment by moagrius** [comment]
try reset, add the new ones, then call `resume`

if that doesn't work post back and i'll try to create an mvp tomorrow

**Comment by krabo0om** [comment]
nope does not work

**Comment by moagrius** [comment]
ok, i'll work on it tonight

**Comment by moagrius** [comment]
maybe i'm misunderstanding the question, because the steps above work fine for me.

grab the latest `master`, then open `RealMapTileViewActivity`, then in some event, put this:

```
getTileView().getDetailLevelManager().resetDetailLevels();

getTileView().setSize( 4015, 4057 );

getTileView().addDetailLevel( 1.000f, "tiles/fantasy/1000/%d_%d.jpg");
getTileView().addDetailLevel( 0.500f, "tiles/fantasy/500/%d_%d.jpg");
getTileView().addDetailLevel( 0.250f, "tiles/fantasy/250/%d_%d.jpg");
getTileView().addDetailLevel( 0.125f, "tiles/fantasy/125/%d_%d.jpg" );

getTileView().resume();
```

You'll see the existing map of Philadelphia get swapped out for Middle Earth...  you'll probably need to re-add markers, etc, but the basic functionality seems fine.

you could also remove the existing TileView and swap it for another, although you'd probably want to make sure that all the bitmaps were cleared first, etc.

post back if you're not seeing the same behavior

**Comment by krabo0om** [comment]
for those maps it does work, however, if there are tiles missing in the new levels it does not clear the old ones.
I created an example [in a fork](https://github.com/krabo0om/TileView) adding a floor plan view. Tapping a marker switches the plans, but the 2nd one is missing a few tiles. This leads to an overlapping (I used transparent .png) of the tiles after the missing ones. If you than zoom in and pan around the problem is fixed (because of the complete re-render of the bitmap I guess).
Would you call this a bug or just an improper use because there are tiles missing?

**Comment by moagrius** [comment]
i noticed #339 when researching this; try the fix mentioned there and see if that does it for you.

i'm a little worried that it might just be an OOME on some tiles, which means either A) not much we can do about it, or B) i need to create a really aggressive clear-type method.  you might want to put logs in the BitmapDecoder catch blocks to see if that's the case...

**Comment by krabo0om** [comment]
I added the line mentioned in #339 but this does not fix it.
Adding logs showed that it's just a file not found error. If I add
`return Bitmap.createBitmap(tile.getHeight(), tile.getWidth(), OPTIONS.inPreferredConfig);`
to the outer catch at `BitmapProviderAssets:45` it displays black tiles (as expected).
Back to returning just null if there is no bitmap:
In `TileCanvasViewGroup.drawTiles()` I ignored `mPreviouslyDrawnTiles` and always called `drawTilesWithoutConsideringPreviouslyDrawnLevel` which fixed it but made the render super slow.

**Comment by moagrius** [comment]
I'll poke around some more tonight

**Comment by moagrius** [comment]
yeah i just checked it, and it's just missing tiles.  see attached screenshot.

note the logs say missing tile 4_3, 1_3, 2_3, 2_4, etc - all of which you can see in the same screenshot are not present in the assets.

However I did find a bug that might have prevented your new detail levels from being recognized as changed, and created issues: #340 

I should get both of those into `master` shortly, but not sure when I'll get a release out

thanks for posting

![screen shot 2016-08-25 at 8 29 10 pm](https://cloud.githubusercontent.com/assets/701344/17991303/fb00a14e-6b02-11e6-9e7a-b15557f44096.png)

**Comment by moagrius** [comment]
actually i was able to get a release out.  try including the missing tiles, and using 2.2.2

**Comment by krabo0om** [comment]
Sorry, I did not made myself clear enough about the missing tiles:
I knowingly and willingly deleted/moved the assets. In my app I get floor plan data from a server, but imagine a |\_| shape like building where there are a few "air" (read `mBitmap=null`) tiles between the | |.
So, if there are tiles without a bitmap during the render, all the following tiles get messed up (when switching to a new set of detail levels). In my case (and the [enhanced demo app](https://github.com/krabo0om/TileView)) they overlap each other (due to them having a lot of transparency).
The better see the effect please checkout the latest version of my fork's demo app. Now it starts with what could be the |_| floor plan (a few tiles missing), but it looks good. Tapping a pin it switches to another floor plan (let's say a regular rectangle basement providing tiles everywhere). Tap a pin again and now it's broken.
Version 2.2.2 did not help, thanks for working on it!

**Comment by moagrius** [comment]
yeah if you have null bitmaps, that's going to confuse a lot of stuff, for example when it's drawing pervious tile sets, it's looking for areas that are not already filled, which null bitmaps will never qualify for.  i'd suggest using empty bitmaps at least.  can you use empty bitmaps (e.g, 1x1 transparent pixels)?

**Comment by krabo0om** [comment]
well that was an easy fix.
in case anybody stumbles over this: add `return Bitmap.createBitmap(new int[]{0}, 1, 1, Bitmap.Config.ALPHA_8)` instead of `return null` in your `BitmapProvider.getBitmap()` implementation.

**Comment by moagrius** [comment]
nice
