### ISSUE TITLE
Path disappears while working with large maps/long paths

### ISSUE THREAD

**Issue by Deliganli** [moagrius/TileView#343]
Hi all,

Path is disappearing after some point if i try to zoom in continuously. Before that there is a very noticable frame drop occurs. But right after path disappeared map works perfectly with a very smooth control. I have found this log;

`09-14 18:04:10.537 21877-22232 W/OpenGLRenderer: Shape too large to be rendered into a texture (12656x2727, max=8192x8192)

The map i am working with is 4000 x 4000 tiled with imagemagick with a similar way in the guides into 256 x 256 jpeg tiles.

My first tought was maybe detecting path's out of visible screen points and not to draw them except the first node. But it won't fix the issue since that one node can be very far as well.

Thank you

**Comment by moagrius** [comment]
Yeah, paths are very resource intensive - I don't think there's anything going on other than what you see in that error message:
```
09-14 18:04:10.537 21877-22232 W/OpenGLRenderer: Shape too large to be rendered into a texture (12656x2727, max=8192x8192)
```
You might try a custom implementation using `drawLines` instead of `drawPath` - you can just extend `DrawablePath` and pass the subclass instance to `TileView.drawPath`, but realistically you're probably just taxing the system too much.  You might try drawing the path into the tiles, or breaking it up into smaller pieces and only rendering what's on screen at render time.

I'm not sure there's much I can offer as far as the library goes.  Closing for now.  Good luck!

**Comment by Deliganli** [comment]
Thanks Mike, i went for canvas.drawLines option on a custom class substitue for CompositePathView which worked with great performance, much better than path object. Only downsides are
1- Not looking great on points where lines meet
2- Cannot draw filled polygons

 thanks very much
