### ISSUE TITLE
Load a single non-tiled image from internet

### ISSUE THREAD

**Issue by eulerdisk** [moagrius/TileView#391]
This is not really a issue, maybe something is missing from the documentation. I was wondering how I can load a single image from internet without knowing its size beforehand.

At the moment the best I can do is this:

```
tileView.setSize( 1920, 1080 );
tileView.addDetailLevel( 1, "https://i.ytimg.com/vi/yaqe1qesQ8c/maxresdefault.jpg", 1920, 1080);
tileView.setBitmapProvider( new BitmapProviderPicasso() );
```
Is there a way without knowing the size ??

**Comment by moagrius** [comment]
tileview is meant to manage tiled images, because large untiled images will often crash low-memory devices. it will not tile the image for you.

the size you provide is the total size of all the tiles that make up a certain level.

if you just want to display a single image with scrolling and flinging, i'd probably just use a ZoomPanLayout that contained an ImageView.  You'd have to find out the size first then set the size, but you can do that with picasso pretty easily, or just extend ZoomPanLayout (in onMeasure, make it as big as it's ImageView child).
