### ISSUE TITLE
Prevent closure of the callout marker

### ISSUE THREAD

**Issue by Amattia** [moagrius/TileView#471]
I have implemented a function that add a marker in a tileView when the screen is touched. 

When I touch a marker a callout is opened, I need that this callout remain opened until an event linked to a botton is triggered.

Actually I have no idea to how prevent the closure of the callout marker.

**Comment by moagrius** [comment]
the only difference between a "marker" and a "callout" is that callouts are removed when a touch event occurs on the TileView: 
https://github.com/moagrius/TileView/blob/master/tileview/src/main/java/com/qozix/tileview/markers/CalloutLayout.java (source) https://github.com/moagrius/TileView/blob/master/tileview/src/main/java/com/qozix/tileview/TileView.java#L807 (the one line of touch event code)

(also, it's a layer higher, but you can manage that manually)

just use the marker api instead of the callout api if you don't want them destroyed on touch.

**Comment by Amattia** [comment]
> just use the marker api instead of the callout api if you don't want them destroyed on touch.

Could you explain to me how please ? sorry but i don't understand...

**Comment by moagrius** [comment]
i showed you the line where callouts are closed.

both markers and callouts are just Views.  if you use addMarker, it's a marker.  if you use addCallout, it's a callout.

the _only_ difference between a "marker" and a "callout" is a that callouts are destroyed onTouch.  if you don't want that, use a marker instead: `addMarker(someView, ...)`
