### ISSUE TITLE
Demo fails to build if I change dependency to implementation 'com.qozix:tileview:3.0.1'

### ISSUE THREAD

**Issue by arfan** [moagrius/TileView#506]
Hi, I can git clone and compile the project, but if I try to modify gradle build in demo to become

`dependencies {
  implementation fileTree(include: ['*.jar'], dir: 'libs')
  testImplementation 'junit:junit:4.12'
  implementation 'com.android.support:appcompat-v7:27.1.1'
  implementation 'com.facebook.stetho:stetho:1.5.0'

  //implementation project(':tileview')
  implementation 'com.qozix:tileview:3.0.1'
}`

Then I cannot build the project. I get errors like this

`error: incompatible types: Plugin cannot be converted to CoordinatePlugin`

Is this to be expected? is there any difference when I include the project with `implementation project(':tileview')` and  ` implementation 'com.qozix:tileview:3.0.1'` ?

Thank you.

**Comment by moagrius** [comment]
I'll try to take a look this weekend. Thanks

**Comment by moagrius** [comment]
This is very strange.  The script I use to compile the public .aar _should_ be using the right version to compile, but for some reason we're losing type inference.  I'll continue to investigate, but if you just just option + enter and those compile errors (there are less than 10, in 1 file, took me about 20 seconds) you can build, but you're right, they should be the same.  I even tried hardcoding the compile version but it made no difference - very strange since it's still clearly getting Java 8 features (like lambdas), it _just_ loses type inference.
